### PR TITLE
Fix Backend implementation to work with cursive 0.11

### PR DESCRIPTION
**Pull request by johnbatty**
Crate fails to build with cursive 0.11+, as the Backend trait definition has been changed.  Fortunately the changes are related to input handling, so are relatively straightforward to fix up.

Errors:
```
error[E0432]: unresolved import `cursive::backend::InputRequest`
  --> src/lib.rs:11:33
   |
11 | use cursive::backend::{Backend, InputRequest};
   |                                 ^^^^^^^^^^^^ no `InputRequest` in `backend`

error[E0407]: method `start_input_thread` is not a member of trait `Backend`
   --> src/lib.rs:199:5
    |
199 | /     fn start_input_thread(
200 | |         &mut self,
201 | |         event_sink: Sender<Option<Event>>,
202 | |         input_request: Receiver<InputRequest>,
203 | |     ) {
204 | |         self.backend.start_input_thread(event_sink, input_request);
205 | |     }
    | |_____^ not a member of trait `Backend`

error[E0407]: method `prepare_input` is not a member of trait `Backend`
   --> src/lib.rs:211:5
    |
211 | /     fn prepare_input(&mut self, input_request: InputRequest) {
212 | |         self.backend.prepare_input(input_request);
213 | |     }
    | |_____^ not a member of trait `Backend`

error[E0046]: not all trait items implemented, missing: `poll_event`
   --> src/lib.rs:184:1
    |
184 | impl Backend for BufferedBackend {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `poll_event` in implementation
    |
    = note: `poll_event` from trait: `fn(&mut Self) -> std::option::Option<cursive::event::Event>`
```

This fix removes the old input functions and replaces them with a passthrough for the new input function.

Many thanks for this crate - I've been happily using it to fix the flickering when using the termion backend.

### CODE REVIEW

**Comment by agavrilov** [comment]
Sorry, I missed the notification about your pull request somehow before fixing the code on my own. The version 0.2.0 is published and it is compatible with Cursive 0.11. I'm closing this pull request,
